# Generated by Django 4.2.3 on 2023-07-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0005_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
